### ISSUE TITLE
Problem with threads

### ISSUE THREAD

**Issue by Archnitest** [hangilk/AP-CS-Arcade#2]
In my Java Swing Window, I have a JFrame. Whenever my Battle.java battle(), lines 30-44 method is called, it freezes my JFrame and it becomes unresponsive. According to my research, this is due to the while loop in the battle() method. It works perfectly fine when I comment out calling Battle.battle in my Dialogue.java, line 49.

I've been trying to use Thread.yield() to fix this but it appears that the Swing frame and the while loop are part of the same Thread. This is strange as a previous version with an error had separated the two into different Threads.

This can be found in my Cards branch.

**Comment by 82hk** [comment]
Well, it looks like Thread.yield() would cause issues (as well as Thread.sleep()) You're basically de-assigning the thread's use over and over again, which basically means the thread will never get back onto the program. In addition, the booleans actioned and turned are changed outside of their respective while loops, which means that it'll never actually get updated.

What you'll need to implement is some kind of boolean or logic that will change depending on the action of the player (inside of the while loops, for example an if statement). or overhaul the current logic you have. (I'm not too sure what route you want to go, but I just outlined the current issue you're having)
