### ISSUE TITLE
Framework Broken?

### ISSUE THREAD

**Issue by Archnitest** [hangilk/AP-CS-Arcade#5]
Well, for some reason, the framework isn't working. There's an import statement in Menu.java that apparently doesn't work.
`import com.google.common.reflect.ClassPath;`
Because of this error, nothing else will run, at least for me.
Help?

**Comment by 82hk** [comment]
The framework isn’t broken; the .jar file that includes that package isn’t part of the project structure. I sent Mr. Eckstein an email to figure out how to implement the .jar automatically but here’s how to do it manually:
File > Project Structure
Find the tab on the side that says “Libraries”
Click the plus button and go to the AP CS Arcade directory. Click the file that has “guava” in it. 
Click “Apply” then the program should run.
